#!/bin/bash

hs=( "0.8" "1.2" "1.8" "2.3" "2.6")
total_hs="${#hs[@]}"
scheme=$1
tmax=$2
casename=$3

if [ ! -d "$casename" ]; then
  mkdir "$casename"
fi

if [ ! -d "$casename/results" ]; then
  mkdir "$casename/results"
fi

if [ ! -d "$casename/results/$scheme" ]; then
  mkdir "$casename/results/$scheme"
fi

if [ ! -d "$casename/plots" ]; then
  mkdir "$casename/plots"
fi

g++ -O3 test.cpp -o testPositivity

for h in "${hs[@]}"; do
  Nf=$(echo "scale=1; $tmax / $h" | bc) 
  N=$(awk -v var="$Nf" 'BEGIN { printf "%.0f\n", var }')
  ./testPositivity $scheme $h $N $casename 60
done

gnuplot_script="${casename}/results/${scheme}/plot_script_$scheme.gp"

N0f=$(echo "scale=1; $tmax / ${hs[0]}" | bc)
N0=$(awk -v var="$N0f" 'BEGIN { printf "%.0f\n", var }')

cat <<EOL > "$gnuplot_script"
set terminal pdfcairo enhanced color size 5,5
set output "${casename}/plots/positivity_${scheme}_t_${tmax}.pdf"
set size square
set xlabel "t [s]" font ',25'
set ylabel "y_{${scheme}}(t)" font ',25'
set xrange [0:${tmax}]
set yrange [-1:1]
set key font ',25'

set xtics font ',20'
set ytics font ',20'

set grid
plot '${casename}/results/${scheme}/testPositivity_${scheme}_h_${hs[0]}_N_${N0}.dat' using 1:2 with linespoints title 'h = ${hs[0]}',\\
EOL

for ((i=1;i<"${#hs[@]}"; i++)); do
  h="${hs[$i]}"
  Nf=$(echo "scale=1; $tmax / $h" | bc) 
  N=$(awk -v var="$Nf" 'BEGIN { printf "%.0f\n", var }')
  data_file="${casename}/results/${scheme}/testPositivity_${scheme}_h_${h}_N_${N}.dat"
  echo "'$data_file' using 1:2 with linespoints title 'h = $h',\\" >> $gnuplot_script
done

# Run Gnuplot with the generated script
gnuplot "$gnuplot_script"

