#!/bin/bash

#SBATCH --job-name="test-mms"
#SBATCH --chdir=.
#SBATCH --ntasks=1

export USER_INSTALL_ROOT=/home/josep.plana/INSTALL
export PATH=$USER_INSTALL_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$USER_INSTALL_ROOT/tf2/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$USER_INSTALL_ROOT/pkgconfig:$PKG_CONFIG_PATH
export TF2_MODS_PATH=$USER_INSTALL_ROOT/tf2/mods

mpirun tf-sim $1

