#!/bin/bash

#SBATCH --chdir=.
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=4
#SBATCH --ntasks-per-node=2
#SBATCH --ntasks-per-socket=2

export OMP_NUM_THREADS=4
export OMP_PLACES=sockets
export OMP_PROC_BIND=spread

export USER_INSTALL_ROOT=/home/josep.plana/INSTALL
export PATH=$USER_INSTALL_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$USER_INSTALL_ROOT/tf2/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$USER_INSTALL_ROOT/pkgconfig:$PKG_CONFIG_PATH
export TF2_MODS_PATH=$USER_INSTALL_ROOT/tf2/mods

srun tf-sim $1

